// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyzmayxchxqrwhnwwesn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5em1heXhjaHhxcndobnd3ZXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDM5MzQsImV4cCI6MjA2MDAxOTkzNH0._-htGKEB4G_RtoReFSA60dxvCTqA_UlUtjInqMwtrB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);